"""Product defaults and thresholds; user-facing overrides are versioned per run."""

MAX_UPLOAD_BYTES = 10 * 1024 * 1024
MAX_EXPECTED_CUSTOMERS = 100_000
MIN_HISTORY_DAYS = 14
DEGRADED_HISTORY_DAYS = 30
DEFAULT_BUFFER = 0.05
DEFAULT_PRODUCTION_INCREMENT = 1
DEFAULT_MODERATE_RISK_RATE = 0.05
DEFAULT_HIGH_RISK_RATE = 0.10
INSIGHTS_DEFAULT_DAYS = 90
